extensions = ["md"]
timeout = 5 # in seconds
accept = [
    "200",
    "418", # status sometimes returned by systemd's doc website
    "429",
    "502", # it's ok if the backend is down during the scan
    "503", # it's ok if the backend is down during the scan
]
exclude = []
